[APP_BEHAVIOR]
mode = "online"
filename.matches = "matches_20_1.pkl"
filename.more_matches = "matches_60.pkl"
filename.match = "match_br_1.pkl"
filename.profile = "profile.pkl"

[API_OUTPUT_FORMAT]
n_loadouts = 3

int_cols =  [
    'assists',
    'bonusXp',
    'challengeXp',
    'damageDone',
    'damageTaken',
    'deaths',
    'executions',
    'gulagKills',
    'gulagDeaths',
    'headshots',
    'kills',
    'longestStreak',
    'matchXp',
    'medalXp',
    'miscXp',
    'nearmisses',
    'rank',
    'score',
    'scoreXp',
    'teamCount',
    'teamPlacement',
    'timePlayed',
    'totalXp',
    'wallBangs'
    ]

float_cols = [
    'kdRatio',
    'percentTimeMoving',
    'distanceTraveled'
    ]

ts_cols = [
    'utcEndSeconds',
    'utcStartSeconds'
    ]

[APP_DISPLAY]
cols.sessions_history = [
    "utcStartSeconds",
    "utcEndSeconds",
    "matchID",
    "mode",
    "teamPlacement",
    "kdRatio",
    "kills",
    "deaths",
    "assists",
    "gulagStatus",
    "loadout_1"
    ]

cols.kd_history = [
    "utcStartSeconds",
    "kdRatio",
    "kdRatioCumAvg",
    "kills",
    "killsCumAvg",

]

cols.match = []
cols.matches = []

labels.utcEndSeconds = 'Ended at'
labels.utcStartSeconds = 'Started at'
labels.timePlayed = 'Playtime'
labels.teamPlacement = '#'
labels.kdRatio = 'KD'
labels.damageDone = 'Damage >'
labels.damageTaken = 'Damage <'
labels.gulagKills = 'Gulag'
labels.headshots = '% headshots'
labels.percentTimeMoving = '% moving'
labels.duration = 'Game duration'
labels.gulagStatus = 'Gulag'
labels.played = 'Matches'
labels.username = 'Player(s)'




# DOCUMENTATION

# [APP_BEHAVIOR]
# mode : "online" or "offline"
# COD API is either inconsistent / or not very permissive. For debug / trial purposes you can set it to run
# as "offline"'. Typical API responses for profile, matches history , match detail are stored in /data
